apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-pedido
  labels:
    name: ms-pedido
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-pedido
  template:
    metadata:
      labels:
        app: ms-pedido
    spec:
      containers:
      - name: ms-pedido
        image: pabloldias/soat1-grupo18-ms-pedido:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "384Mi"
            cpu: "2000m"
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://fiap-ms-pedido.cr0dnn5xiohv.us-east-1.rds.amazonaws.com:5432/fiap_ms_pedido
        - name: SPRING_DATASOURCE_USERNAME
          value: dbuser # Bad practice. It should be a secret.
        - name: SPRING_DATASOURCE_PASSWORD
          value: dbpassword # Bad practice. It should be a secret.
        - name: AWS_REGION
          value: us-east-1
        - name: AWS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_access_key
        - name: AWS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws_secret_key
        - name: AWS_SNS_ENDPOINT
          value: "sns.us-east-1.amazonaws.com"
        ports:
        - containerPort: 8080
